require:
  - standard
  - rubocop-rails
  - rubocop-performance
  - rubocop-rubycw

inherit_gem:
  standard: config/base.yml

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.3
  TargetRailsVersion: 7.1
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
